### ISSUE TITLE
Reference to element is wrong when morphed onto exiting DOM

### ISSUE THREAD

**Issue by tornqvist** [choojs/nanocomponent#32]
I'm building an isomorphic app (using [choo](https://github.com/yoshuawuyts/choo)) where the server renders to string and the clients mounts the application on the existing DOM node. I'm actually using [microcomponent](https://github.com/yoshuawuyts/microcomponent) but noticed an issue with the underlying mechanisms of nanocomponent. When mounting (using [nanomnorph](https://github.com/yoshuawuyts/nanomorph)) only the attributes from the client rendered nodes are copied to the existing nodes, this has the effect that the reference to `this._element` in nanocomponent is not the element that is in the actual DOM, but that which was used by nanomorph for diffing. This causes any subsequent calls to `morph` with `this._element` to have no effect since they are morphing an element that is not in the DOM.

I would have made a PR but was unsure where this issue should be addressed.

Here's a requirebin that illustrates the issue (see console for output):
http://requirebin.com/?gist=b82e86737dd91c5a2c80d49e64d30684

**Comment by bcomnes** [comment]
Should be fixed in 6.0.0-0 forward as this was a key problem I aimed to fix there.  Unfortunately there are some significant changes you will have to absorb as well.  Closing for now.  We can reopen if we can reproduce 6.0.0 forward.
