### ISSUE TITLE
'load' and 'unload' events are not called when using electron (node integration)

### ISSUE THREAD

**Issue by ojack** [choojs/nanocomponent#62]
I am getting strange behavior when I use electron's built-in node integration to require nanocomponent rather than browserify.

When running the nanocomponent examples within electron, 'load' and 'unload' events are never called, even though the element is mounted to and removed from the dom. No errors are logged, and the rest of the events, including 'beforerender' all seem to behave as documented. 

i don't know enough about any of the involved projects to know why there would be a difference/whether it is expected! 
I can include more information + code if it is helpful =]

**Comment by bcomnes** [comment]
Can you confirm you are running 6.4.2?  Also what version of electron are you running?

**Comment by ojack** [comment]
version 6.4.2 of nanocomponent, version 6.3.0 of choo, and version 1.6.11 of electron

**Comment by bcomnes** [comment]
Hrmm... I'll verify this weekend.  Our tests run in electron actually (via https://github.com/juliangruber/tape-run) so they work to some extent.  

If you have a code example that reproduces the issue that would be super helpful.

**Comment by ojack** [comment]
oops, just seeing this now! 

I uploaded an example at https://github.com/ojack/nanocomponent-onload

**Comment by bcomnes** [comment]
Whats probably going on is that the https://github.com/shama/on-load/blob/master/server.js version is getting loaded instead of the actual module.

**Comment by bcomnes** [comment]
We should add an explicit test to that file to check if its running in an electron environment and load in the correct version if thats the case.  Sorry to take so long on this, but occurred to me in the shower the other day.

**Comment by bcomnes** [comment]
This will be closed by https://github.com/shama/on-load/pull/32

**Comment by bcomnes** [comment]
@ojack should be working now.  Sorry for the long delay in gettin this fixed.

**Comment by bcomnes** [comment]
Closing, let me know if there are any other issues.
