### ISSUE TITLE
this.element is null while server rendering?

### ISSUE THREAD

**Issue by nyenye** [choojs/nanocomponent#83]
I've made a nanocomponent, but this.element is undefined while server rendering, and it makes bankai stop when I try to do anything with it, in my case calling getElementsByClassName().

As you can see int the screeshot, it works fine on the browser. Any ideas? Am I doing something wrong, or could this be an issue?

![image](https://user-images.githubusercontent.com/11387253/40583317-66c3a396-618c-11e8-9a1f-42f8c9ed1ec5.png)

(I'm using an example from Bootstrap as template)

[test-choojs.zip](https://github.com/choojs/nanocomponent/files/2042330/test-choojs.zip)

**Comment by bcomnes** [comment]
This is expected behavior. This.element returns the DOM node mounted in the page. Since there is only a string representation during server rendering, this.element is always null in that context.

**Comment by nyenye** [comment]
I feared this would be the case. In that case, what could I do to keep the bankai server running? It halts when calling a function from this.element.

**Comment by bcomnes** [comment]
You can test and guard for it by testing for this.element or use something like typeof window !== 'undefined'

**Comment by nyenye** [comment]
Thanks. Will close then!

**Comment by bcomnes** [comment]
NP good luck!  Feel free to ask questions in IRC as well.  Server rendering with stateful components is a tricky problem.

**Comment by nyenye** [comment]
Oh good to know there's an IRC channel. Other sites like stackoverflow are not very useful when using lesser known frameworks and I opted to open an issue. Thanks again!
