### ISSUE TITLE
Image(s) not loading after navigation

### ISSUE THREAD

**Issue by fsteff** [choojs/nanocomponent#92]
I ran into the problem of images not loading after navigation.
I am not sure if this is a bug or if it's just me not understanding something correctly...

With this little app I was able to reproduce the problem:

```javascript
const choo = require('choo')
const html = require('choo/html')
const Nanocomponent = require('nanocomponent')

class Image extends Nanocomponent {
  constructor (image) {
    super()
    this.image = image
  }

  createElement () {
    console.log(`rendering ${this.image}`)
    return html`<img src="${this.image}" alt="${this.image}" style="width: 100px;">`
  }

  update () {
    return true
  }
}

class Viewer extends Nanocomponent {
  createElement (state) {
    const container = html`<div>
   <h3>Images:</h3><p>
   <a href="/?img1=1&img2=1&img3=1">back to the overview</a>
   </p></div>`
    if(state.query.img1) 
      container.append(html`<a href="/?img1=1&img2=1"><p>1:</p>${img1.render()}</a>`)
    if(state.query.img2) 
      container.append(html`<a href="/?img2=1&img3=1"><p>2:</p>${img2.render()}</a>`)
    if(state.query.img3) 
      container.append(html`<a href="/?img3=1&img2=1"><p>3:</p>${img3.render()}</a>`)
    return container
  }

  update () {
    return true
  }
}

const img1 = new Image('1.jpg')
const img2 = new Image('2.jpg')
const img3 = new Image('3.jpg')
const viewer = new Viewer()

const app = choo()
app.mount('body')

app.route('/index.html', main)
app.route('/', main)

function main(state, emit){
  return html`<body>
    ${viewer.render(state)}
  </body>`
}
```

It shows multiple images, depending on the URL query.
Each image is a link that leads to another page that shows this image and one other. (with the same structure) 

Reproducing the problem works in 4 steps:
1. `/` - no image displayed -> click on "overview"
2. `/?img1=1&img2=1&img3=1` - all 3 images are displayed -> click on the first
3. `/?img1=1&img2=1` - image 1 and 2 are displayed -> click on the second
4. `/?img2=1&img3=1` - *image 2 should be displayed, but doesn't get loaded*, image 3 is ok

The html looks like the following (no src and alt property!):
`<img data-nanocomponent="ncid-5f7b" id="ncid-5f7b" data-proxy="">`
According to the log the component is re-rendered.
The element id stays the same (I assume this is expected).

I don't know much about the internals of choo/nanocomponent, so I am pretty helpless on my own. Thanks very much in advance!

EDIT:
I am using choo and nanocomponent only in the browser using browserify. 
Versions: 
```
"choo": "^6.13.3", 
"nanocomponent": "^6.5.2"
```

**Comment by tornqvist** [comment]
I'ts a known issue that nanocomponent doesn't like being moved around in the DOM. Since a DOM node can't exist in two places at once, nanocomponent updates in place and if the order is changed the node is lost.

The best way to mitigate this is to ensure that the DOM tree remains the same in-between states, one way of doing that is to have containers for the three images and just leave the containers empty if an image shouldn't be shown, like this:

```javascript
lass Viewer extends Nanocomponent {
  createElement (state) {
    return html`
      <div>
        <h3>Images:</h3>
        <p>
          <a href="/?img1=1&img2=1&img3=1">back to the overview</a>
        </p>
        <div>
          ${state.query.img1 ? html`
            <a href="/?img1=1&img2=1"><p>1:</p>${img1.render()}</a>
          ` : null}
        </div>
        <div>
          ${state.query.img2 ? html`
            <a href="/?img2=1&img3=1"><p>2:</p>${img2.render()}</a>
          ` : null}
        </div>
        <div>
          ${state.query.img3 ? html`
            <a href="/?img3=1&img2=1"><p>3:</p>${img3.render()}</a>
          ` : null}
        </div>
      </div>
    `
  }

  update () {
    return true
  }
}
```

Here's a working example: https://glitch.com/edit/#!/blushing-gull?path=index.js

**Comment by fsteff** [comment]
Thanks for the fast reply!
For the project I am working on this solution won't be possible, so I think I'll just create a new instance each time I render it.

**Comment by bcomnes** [comment]
Additionally, if you don't need on-load or state, you can skip wrapping images in components. Thank you @tornqvist for the explanation.

**Comment by fsteff** [comment]
Thanks for your help, resolved.
